### ISSUE TITLE
Many-to-many relationships?

### ISSUE THREAD

**Issue by ssfinney** [laracasts/TestDummy#17]
I know I can do the below example for a one-to-many relationship in TestDummy.

```
Post:
  title: Hello World $string
  body: $text
  published_at: $date
  author_id:
    type: Author

Author:
    name: John Doe $integer
```

But how do I do a many-to-many relationship? This requires defining a pivot table, which I can't define in the ```fixtures.yml``` file.
