### ISSUE TITLE
Can't embed random value in an attribute without spaces

### ISSUE THREAD

**Issue by luukholleman** [laracasts/TestDummy#18]
Seems i can't create values where an random value is generated inside a string without spaces. Like:

```
User:
  email: $string@example.com
  password: string
  ...
```

It will only accept `$string @example.com` which is of course not a valid email.
