### ISSUE TITLE
One To One Relationships

### ISSUE THREAD

**Issue by PatrickRose** [laracasts/TestDummy#27]
The app I'm currently building has users able to link to another user as a one to one relationship. However, TestDummy doesn't particularly like that since it recursively creates more and more User objects and then blows up.

Example yaml file

```yaml
User:
  email: $string@$string.com
  password: $string
  fiance_id:
      type: User
```
